server:
  port: 8412
  servlet:
    session:
      cookie:
        http-only: false
      timeout: 7200 # 秒  120分钟 = 7200秒

spring:
  application:
    name: admin-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # %2b表示+号
    url: jdbc:mysql://localhost:3306/admin_template?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Swagger API文档配置
  servlet:
    multipart: # 上传文件大小限制
      enabled: true
      max-file-size: 50MB      # 上传单个文件最大值
      max-request-size: 100MB  # 上传文件总的最大值

mybatis:
  type-aliases-package: com.example.backend.entity
  mapper-locations: classpath:mapper/*.xml

project-config:
  env: production
  config-name: application.yml
  site-id: develop
